apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    status: "deployment"
    responsable: "Juan"
spec:
  containers:
   {{$version := "9.0"}}
   - name: tomcat1
     image: tomcat:{{$version}}
