apiVersion: v1
kind: Pod
metadata:
  name: {{.Release.Name}}-nginx1
  labels:
    zone: example
    version: production
  annotations: {
    namespace: name-{{.Release.Namespace}},
    upgrade: upgrade-{{.Release.IsUpgrade}},
    install: install-{{.Release.IsInstall}},
    revision: revision-{{.Release.Revision}}
    }
spec:
  containers:
   - name: nginx
     image: apasoft/nginx:v1
