apiVersion: v1
kind: Pod
metadata:
  name: {{.Release.Name}}-tomcat
  labels:
    status: "approved"
    responsable: "Juan"
spec:
  containers:
   - name: tomcat1
     {{- if eq .Values.environment "development" }}
     image: tomcat:9.0
     {{ else }}
     image: tomcat:10.0
     {{ end }}
